name: test-targets-in-container

on:
  push:
    branches:
      - enhancement/*
      - fix/*
      - feature/*
      - hotfix/*
  workflow_dispatch:

jobs:
  test-targets:
    runs-on: ubuntu-latest

    # run the steps inside image
    container:
      image: colebrookson/r-hpc-reproducible-repo:latest

    steps:
      # checkout the code
      - uses: actions/checkout@v4

      # (optional) load .env if present
      - name: load env
        run: |
          if [ -f .env ]; then
            export $(grep -v '^#' .env | xargs)
          fi

      # run pipeline
      - name: run targets pipeline
        run: Rscript -e "targets::tar_make()"
