name: test-targets-in-container

on:
  push:
    branches:
      - enhancement/*
      - fix/*
      - feature/*
      - hotfix/*
  # pull_request:
  #   branches:
  #     - main
  #     - master
  #     - dev
  workflow_dispatch:
    branches:
      - '*'
  #schedule:
  #  - cron: "0 13 * * 2"
      
jobs:
  test-targets:
    runs-on: ubuntu-latest                                
    # run the actions inside my own image
    container:
      image: colebrookson/r-hpc-reproducible-repo:latest
      # if image needs environment vars, you can add:
      # env:
      #   CRAN_MIRROR: https://cloud.r-project.org
      
        steps:
      # checkout latest code
      - uses: actions/checkout@v4

      # (optional) pull in any environment files
      - name: load env
        run: |
          if [ -f .env ]; then
            export $(grep -v '^#' .env | xargs)
          fi

      # run pipeline
      - name: run targets pipeline
        run: |
          Rscript -e "targets::tar_make()"